config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :dashboard, only: [:show]
  resources :tags, only: [] do
    member do
      get '/:address', action: 'show', as: :of
    end
  end
end

app/models/admin_user.rb
# == Schema Information
#
# Table name: admin_users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Tag < ApplicationRecord
  has_many :tweets
  validates_uniqueness_of :name
end

app/models/tweet.rb
# == Schema Information
#
# Table name: tweets
#
#  id         :integer          not null, primary key
#  text       :string
#  tweeted_at :datetime
#  metadata   :jsonb
#  address    :string
#  lat        :string
#  long       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  tag_id     :integer
#

class Tweet < ApplicationRecord
  store :metadata, accessors: %i[user payload]
  reverse_geocoded_by :lat, :long
  geocoded_by         :address, latitude: :lat, longitude: :long

  after_validation :geocode,         if: ->(obj) { obj.address.present? && obj.address_changed? }
  after_validation :reverse_geocode, if: ->(obj) { obj.lat_changed? || obj.long_changed? }

  scope :from_, ->(address) { where(address: address).order(tweeted_at: :desc) }
  belongs_to :tag

  class << self
    def create_from(tweet, tag = nil)
      new_tweet = new
      new_tweet.text = tweet.text
      new_tweet.payload = tweet.to_hash
      new_tweet.fill_address_from_(tweet)
      new_tweet.tweeted_at = tweet.created_at
      new_tweet.tag = tag
      new_tweet.save

      new_tweet
    end
  end

  def fill_address_from_(tweet)
    if tweet.geo?
      self.lat = tweet.geo.latitude
      self.long = tweet.geo.longitude
      # Address will be auto-generated by `GeoCoder`
    elsif tweet.place?
      self.address = tweet.place.full_name # Indicates full address
    else
      self.address = tweet.user.location
      # Lat, Long will be auto-generated by `GeoCoder`
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string
#  last_name              :string
#  provider               :string
#  uid                    :string
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: %i[twitter]

  class << self
    def from_omniauth_twitter(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        # Since twitter does not provide us email address in response
        user.email       = "#{auth.info.nickname}@twitfeed.in"
        user.password    = Devise.friendly_token[0, 20]
        user.first_name  = auth.info.first_name
        user.last_name   = auth.info.last_name
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  layout 'devise', if: :devise_controller?

  private
    def after_sign_in_path_for(resource)
      sign_in_url = new_user_session_url
      if request.referer == sign_in_url
        super
      else
        stored_location_for(resource) || dashboard_path
      end
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  layout 'dashboard'

  def show
    tweets        = Tweet.includes(:tag).where.not(address: nil).distinct
    @tweets_count = tweets.count
    @data         = pagination_for(tweets)
    @chart_data   = Tweet.group('date(tweeted_at)').group(:tag_id)
                         .count
                         .group_by { |array_of_date, _| array_of_date[0] }
  end

  private

  def pagination_for(tweets)
    Kaminari.paginate_array(data_for_panels_from(tweets)).page(params[:page])
  end

  def data_for_panels_from(all_tweets)
    # Will give data formatted like
    # [1, 'Nepal', 12]
    format = ->(tag, tweets) { [tag.id, tag.name, tweets.count] }

    all_tweets.group_by(&:address)
              .map do |address, tweets|
                [address, tweets.group_by(&:tag).map(&format)]
              end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout 'static'
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!
  layout 'dashboard'

  def show
    @tag = Tag.find(params[:id])
    @tweets = @tag.tweets.from_(params[:address])
    @tweets_count = @tweets.count
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    @user = User.from_omniauth_twitter(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Twitter') if is_navigational_format?
    else
      session['devise.twitter_data'] = request.env['omniauth.auth'].except('extra')
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def embed_clickable_links_from(text)
    simple_format(text)
      .gsub(URI.regexp, '<a href="\0" target="_blank">\0</a>')
      .html_safe
  end

  def chart_data
    
    text = ''
    @chart_data.each do |key, value|
      text << "{date: '#{key}',\n"
      value.each do |val|
        text << "#{tags_data[val[0][1]]}: #{val.last},\n"
      end
      text << "},\n"
    end

    text
  end

  def tags_data 
     Tag.all.map {|x| [x.id, x.name]}.to_h
  end

  def map_url
    address = params[:address].gsub(/[Uu]nnamed\s[Rr]oad,\s/, '')
    zoom_level = address == params[:address] ? 17 : 13
    "https://www.google.com/maps/embed/v1/search?q=#{URI.encode(address)}"\
    "&zoom=#{zoom_level}&key=#{ENV['GMAP_API']}"
  end
end

app/views/application/_flash.slim
- if flash[:notice].present?
  .the-flash.alert.alert-success.main_alert[role="alert"]
    a.close href="#" data-dismiss="alert" aria-label="close" &times;
    = flash[:notice]
- elsif flash[:error].present?
  .the-flash.alert.alert-danger.main_alert[role="alert"]
    a.close href="#" data-dismiss="alert" aria-label="close" &times;
    = flash[:error]

/ Alert might coexists with other flash types
- if flash[:alert].present?
  .the-flash.alert.alert-warning.main_alert[role="alert"]
    a.close href="#" data-dismiss="alert" aria-label="close" &times;
    = flash[:alert]

app/views/dashboards/show.slim
.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        |  Trends of Tweets per tag
      .panel-body
        #morris-area-chart
h3 Locations
#accordion.panel-group[role="tablist" aria-multiselectable="true"]
  - @data.each.with_index do |row, index|
    .panel.panel-default
      #headingOne.panel-heading[role="tab"]
        h4.panel-title
          a[role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse#{index}" aria-expanded="true" aria-controls="collapseOne"]
            = row[0]
      .panel-collapse.collapse.in[role="tabpanel" aria-labelledby="headingOne" id="collapse#{index}"]
        .panel-body
          ul.list-group
            - row[1].each do |tag_data|
              li.list-group-item
                span.badge
                  = tag_data[2]
                = link_to of_tag_path(tag_data[0], row[0]) do
                  i.fa.fa-tag 
                  ' 
                  = tag_data[1]
= paginate @data

javascript:
    Morris.Area({
        element: 'morris-area-chart',
        data: [
          #{chart_data.html_safe}
        ],
        xkey: 'date',
        ykeys: #{tags_data.values.inspect.html_safe},
        labels: #{tags_data.values.inspect.html_safe},
        pointSize: 2,
        hideHover: 'auto',
        resize: true
    });

app/views/layouts/dashboard.html.slim
doctype html
html
  head
    meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0" <!--320-->
    title
      | TwitFeed
    = csrf_meta_tags
    = stylesheet_link_tag    'dashboard', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'dashboard', 'data-turbolinks-track': 'reload'
    link href="/favicon.ico" rel="shortcut icon"
    meta name="viewport" content="width=device-width, initial-scale=1"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    
body
  = render 'flash'
  #wrapper
    nav.navbar.navbar-default.navbar-static-top[role="navigation" style="margin-bottom: 0"]
      .navbar-header
        button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
          span.sr-only
            | Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
        = link_to root_path, class: 'navbar-brand' do
          = image_tag 'logo.png', class: 'img-responsive pull-left', width: 20
          | TwitFeed
      ul.nav.navbar-top-links.navbar-right
        li.dropdown.pull-right
          a.dropdown-toggle[data-toggle="dropdown" href="#"]
            i.fa.fa-user.fa-fw
            i.fa.fa-caret-down
          ul.dropdown-menu.dropdown-user
            li
              = link_to destroy_user_session_url, method: :delete do
                i.fa.fa-sign-out.fa-fw
                |  Logout
      .navbar-default.sidebar[role="navigation"]
        .sidebar-nav.navbar-collapse
          ul#side-menu.nav
            li.sidebar-search
              .input-group.custom-search-form
                input.form-control[type="text" placeholder="Search..."]
                span.input-group-btn
                  button.btn.btn-default[type="button"]
                    i.fa.fa-search
            li
              = link_to dashboard_path do
                i.fa.fa-dashboard.fa-fw
                |  Dashboard


    #page-wrapper
      .row
        .col-lg-12
          h1.page-header 
            | Dashboard
          .row
            .col-lg-3.col-md-6
              .panel.panel-primary
                .panel-heading
                  .row
                    .col-xs-3
                      i.fa.fa-twitter.fa-5x
                    .col-xs-9.text-right
                      .huge
                        = @tweets_count
                      div
                        | Tweets
                  .clearfix
          = yield

app/views/layouts/devise.slim
doctype html
html
  head
    meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0" <!--320-->
    title
      | TwitFeed
    = csrf_meta_tags
    = stylesheet_link_tag    'static', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'static', 'data-turbolinks-track': 'reload'
    link href="/favicon.ico" rel="shortcut icon"
  body
    header#top.header
      .text-vertical-center
        = image_tag 'logo.png', width: '100'
        h1
          | TwitFeed
        h3
          | Find what's TwitFeed
        br
        hr
        .parent
          .align-left.display-table.margin-auto.text-left
            = yield

app/views/layouts/static.html.slim
doctype html
html
  head
    meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0" <!--320-->
    title
      | TwitFeed
    = csrf_meta_tags
    = stylesheet_link_tag    'static', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'static', 'data-turbolinks-track': 'reload'
    link href="/favicon.ico" rel="shortcut icon"
  body
    = yield

app/views/pages/home.slim
header#top.header
  .text-vertical-center
    = image_tag 'logo.png', width: '100'
    h1
      | TwitFeed
    h3
      | Find what's New in Cricket World
    br
    - if current_admin_user.present?
      = link_to admin_root_path, class: 'btn btn-dark btn-lg margin10all' do
        i.fa.fa-dashboard
        |  Goto Admin Panel
    - else 

      - if current_user.present?
        = link_to dashboard_path, class: 'btn btn-dark btn-lg margin10all' do
          i.fa.fa-dashboard
          |  Goto Dashboard
      - else
        = link_to user_twitter_omniauth_authorize_path, class: 'btn btn-dark btn-lg margin10all bg-twitter-color' do
          i.fa.fa-twitter
          |  Just In Minute, Sign In with Twitter
        br
        = link_to user_session_path, class: 'btn btn-dark btn-lg margin10all bg-primary-color' do
          i.fa.fa-user
          |  Just Sign In
        

        = link_to new_admin_user_session_path, target: :_blank, class: 'btn btn-dark btn-lg margin10all bg-facebook-color' do
          i.fa.fa-user
          |  Admin Sign In


.container
  .row
    .col-lg-10.col-lg-offset-1.text-center
      h4
        strong
          | Find #Me
      p
        | New Ashok Nagar
        br
        | New Delhi, 110096
      ul.list-unstyled
        li
          i.fa.fa-phone.fa-fw
          |  +91-123 456 7890
        li
          i.fa.fa-envelope-o.fa-fw
          a[href="mailto:twitfeed@example.com"]
            | info@twitfeed.in
      br
      ul.list-inline
        li
          a[href="#"]
            i.fa.fa-facebook.fa-fw.fa-3x
        li
          a[href="#"]
            i.fa.fa-twitter.fa-fw.fa-3x
        li
          a[href="#"]
            i.fa.fa-dribbble.fa-fw.fa-3x
      hr.small
      p.text-muted
        | Copyright © twitfeed #{Date.today.year}

app/views/tags/show.slim
.panel.panel-default
  .panel-heading
    i.fa.fa-clock-o.fa-fw
    |  Tweets Timeline for "#{@tag.name}" from "#{params[:address]}" area
  .panel-body
    ul.timeline
      - @tweets.each do |tweet|
        li
          .timeline-badge
            i.fa.fa-twitter
          .timeline-panel
            .timeline-heading
              h4.timeline-title
                /= link_to "https://twitter.com/statuses/#{tweet.payload['id']}", target: '_blank' do
                  /= tweet.payload[:user][:name]
                  /|  (@#{tweet.payload[:user][:screen_name]})
              p
                small.text-muted
                  i.fa.fa-clock-o
                  ' 
                  span title="#{tweet.tweeted_at}"
                    = time_ago_in_words(tweet.tweeted_at)
                  |  ago via Twitter
            .timeline-body
              p
                = embed_clickable_links_from(tweet.text)
    hr